- .babelrc
- .travis.yml
- README.md
- fixtures/should-cover.js
- fixtures/should-not-cover.js
- package.json
- src/index.js
- test/babel-plugin-istanbul.js
I've tested this, and I believe it's ready for prime time:
* I've added tests (we'll probably want to build this suite out a bit further).
* I've wired up coverage (working from @gotwarlost's gist).
* I've added the ability to include/exclude files using nyc's syntax.
* I've pulled together a README using @dtinth's as a basis.
Next thing I'm going to do, is move `nyc` into the `istanbuljs` organization, @gotwarlost you're comfortable with `nyc` becoming `istanbuljs`' command-line interface going forward?
If so, I'm going to update the documentation accordingly, and release version `7.x.x` of nyc -- the main difference being that it will no longer load a `.istanbul.yml` (at least for the time being) -- instead, my goal will be to expose any configuration options necessary for istanbuljs in …
> feat: port functionality from __coverage__, get ready for first release

- src/index.js
> Pass realpath(process.cwd()) to test-exclude

- src/index.js
some libraries like ava change the `process.chdir()`, for file include/exclude rules we should stick with the value of `NYC_CWD` if it's available.
see: https://github.com/istanbuljs/nyc/issues/305
> fix: keep using NYC_CWD if available

- package.json
There's currently a bunch of stuff in the npm package which doesn't need to be there:
https://npmcdn.com/babel-plugin-istanbul@1.0.3/
Adding a `files` whitelist is a simple way to prevent it from being included at packing time.
> Add files config to package.json to whitelist lib/

- README.md
- fixtures/plugin-should-cover.js
- fixtures/plugin-should-not-cover.js
- src/index.js
- test/babel-plugin-istanbul.js
PR for #9 
From my testing, plugin options are set to `{}` when not provided, so I'm using being non-empty as the heuristic for using them instead of providing package.json lookup configuration.
Just merging `opts` into the existing config in `shouldSkip` would be a bit more straightforward, but I wasn't sure which versions of Node.js this plugin targets to know if I could use `Object.assign` or would need to pull in or write an alternative implementation.
> Allow exclude/include options to be passed as Babel plugin config

- .travis.yml
- package.json
- src/index.js
- test/babel-plugin-istanbul.js
- test/mocha.opts
switch lodash.assign (which has been deprecated) to object-assign.
to get Node 0.10 tests running, I added a temporary (very _ugly_) hack to address mock-fs issues (CC: @motiz88
> fix: switch deprecated lodash.assign for object-assign

- README.md
- fixtures/has-inline-source-map.js
- package.json
- src/index.js
- test/babel-plugin-istanbul.js
If a source map is explicitly passed, prefer that, otherwise try and pluck an inline source map that babel may have already parsed from the file content.
Counterpart to - https://github.com/istanbuljs/istanbul-lib-instrument/pull/23/files#diff-c07343828715f64179d26d4c237cb63c
Ref - https://github.com/istanbuljs/istanbul-lib-source-maps/pull/4
Context - upstream PR for https://github.com/facebook/jest/pull/2290. Jest provides instrumentation using babel-plugin-istanbul, and currently there's disparity with source map support between `createInstrumenter().instrumentSync()` and this babel plugin. This PR resolves that so both approaches can thread a source map through and have it attached to coverage.
> Accept source map input for the visitor

- fixtures/issue-78.js
- package.json
- test/babel-plugin-istanbul.js
should address regression discussed in #78
> fix: address regression related to export const foo = () => {}

- .travis.yml
- README.md
- package.json
- test/babel-plugin-istanbul.js
BREAKING CHANGE: I've updated dependencies and dropped Node 0.10 and Node 0.12 support.
* we've also pulled in the new version of test-exclude that excludes `/coverage`.
* and dropped `mock-fs` (I liked these tests, but mock-fs seems to run _really_ slow on some versions of Node.js unfortunately).
> feat: drop Node 0.10 and 0.12 support

- package.json
- src/index.js
- test/babel-plugin-istanbul.js
If present, we should load configuration from `process.env.NYC_CONFIG` this adds tests to the work undertaken by @alpersogukpinar in #84.
fixes #82
> fix: load configuration from process.env.NYC_CONFIG if present

- src/index.js
- test/babel-plugin-istanbul.js
This allows reporting on all instrumented files even if they are not `require`d.
> feat: add includeUntested option to expose coverage of all instrumented files

- package.json
explicitly upgrade to instrumenter with @tomchentw's support for named exports.
> chore: explicitly upgrade instrumenter

- package.json
- src/index.js
Adding this plugin allows Babel to parse the syntax. It does _not_ transpile it, so the user still needs to transpile it if running on a node version which does not support it. But this means that consumers don't have to add this plugin just so Babel can parse their code.
Will fix https://github.com/facebook/jest/issues/5082
> fix: include object-spread-syntax plugin

- package.json
address bad release of istanbul-lib-instrument.
> chore: explicit update of istanbul dependencies

- .babelrc
- .travis.yml
- package-lock.json
- package.json
- src/index.js
- test/babel-plugin-istanbul.js
BREAKING CHANGE: Drop node 4 support, upgrade to babel 7.
This is makes use of what is currently istanbul-lib-instrument@next and test-exclude@next.  Note I was not able to find documentation about `this.file.inputMap.sourcemap` - this was found by dumping and inspecting `this.file`, looking for the object matching `this.file.opts.inputSourceMap` from babel@6.
> feat: Upgrade to babel 7, drop Node 4 support.

- package-lock.json
- package.json
This causes the plugin to use the non-beta release of babel 7.
> feat: Bump dependencies.

- fixtures/should-respect-cwd.js
- src/index.js
- test/babel-plugin-istanbul.js
Well, this one took a while.
Long story short, sometimes during runtime, the `cwd` in `opts` for `shouldSkip` does change (e.g. a multi-project Jest setup) through `babel-jest` https://github.com/facebook/jest/blob/master/packages/babel-jest/src/index.js#L125-L134, and if `exclude` https://github.com/istanbuljs/babel-plugin-istanbul/blob/master/src/index.js#L19 isn't 'redone' at that point, it will falsely exclude files from instrumentation (as it's using the previous/initial cwd).
I believe this is the cause for numerous missing coverage issues in multi-project setups. I'm only aware of Jest issues https://github.com/facebook/jest/issues/5417 https://github.com/facebook/jest/issues/5457 https://github.com/facebook/jest/issues/6483, which is what we're using, but there might be others.
In …
> fix: respect changes of cwd in options

- fixtures/with-changed-scope.js
- package-lock.json
- package.json
- src/index.js
- test/babel-plugin-istanbul.js
(Replaces https://github.com/istanbuljs/istanbuljs/pull/283)
This fixes a bug that can be seen when istanbul coverage is enabled for a babel@7 project which uses reference replacement, such as `babel-plugin-lodash` or` babel-plugin-ramda`.
The root issue is that plugins like these assume that scope references will always be Identifiers but Istanbul may replace an identifier with a SequenceExpression. In babel@7 this replacement overwrites the existing scope reference and later plugin scope reference replacement is at best unsafe and at worst may result in an invalid AST.
This seems like a pretty unfortunate situation, and ideally Babel automatically maintains these scope references during transforms or the many packages using scope would account for this situation. The pattern I see in …
> fix: Ensure correct scope references after traversal

- .babelrc
- babel.config.js
- package-lock.json
- package.json
- src/index.js
- test/babel-plugin-istanbul.js
Also simplify the src -> lib transpile to only process ESM -> CJS, nothing else from `@babel/preset-env` is needed by node.js 6.
> fix: Print explicit error if use with babel 6 is attempted

- .gitignore
- fixtures/node_modules/should-cover.js
- fixtures/node_modules/should-not-cover.js
- src/index.js
- test/babel-plugin-istanbul.js
This PR is part of resolving [issue #898](https://github.com/istanbuljs/nyc/issues/898). The idea is to be able to turn off the default exclusion of `**/node_modules/**` for users that need/want to support local `node_modules`. As mentioned in that issue, the `negateExclude` (i.e. `!**/node_modules/**`) doesn't work for cases when you still want your exclusion list to still exclude matches within your local `node_modules` directory. 
Related PRs for solving the above issue:
- https://github.com/istanbuljs/istanbuljs/pull/213
- https://github.com/istanbuljs/nyc/pull/912
**NOTE:** this test-exclude PR (https://github.com/istanbuljs/istanbuljs/pull/213) will need to get merged and published before this is effective.
> Support turning off node_modules default exclude via flag

- fixtures/node_modules/should-cover.js
- fixtures/node_modules/should-not-cover.js
- fixtures/plugin-should-cover.js
- fixtures/plugin-should-not-cover.js
- fixtures/should-cover.js
- fixtures/should-not-cover.js
- fixtures/should-respect-cwd.js
- package-lock.json
- package.json
Upgrades [JavaScript Standard Style](https://standardjs.com) to v14.2.0 and fixes a few [prefer-const](https://eslint.org/docs/rules/prefer-const) errors. Closes #219.
> Upgrade standard to v14.2.0

- fixtures/class-functions.js
- src/index.js
- test/babel-plugin-istanbul.js
This adds support for:
* coverageVariable
* coverageGlobalScope
* coverageGlobalScopeFunc
* ignoreClassMethods
Fixes #208, fixes #212
> feat: Add support for instrumenter options

- .github/workflows/ci.yaml
- package.json
- src/index.js
- test/babel-8/package.json
- test/babel-plugin-istanbul.js
Hi!
The Babel 8 release is almost ready, and we are only waiting until major packages in the Babel ecosystem are ready.
This PR makes `babel-plugin-istanbul` work with both Babel 7 and Babel 8, testing both versions in CI :)
It's one of the blockers that I found when try to update Jest to use Babel 8 by default (cc @SimenB, since I see you in both orgs :P)
Fixes #298
Closes #299
> Add support for Babel 8

- package.json
See https://docs.npmjs.com/cli/v8/using-npm/scripts#life-cycle-scripts. `prepublish` runs after `npm install`, rather than on publish, which is probably not intended.
That's why tests are currently also running when using `npm install`.
> Use `prepublishOnly` instead of `prepublish` for npm scripts
